class Board:
    def print_board(self, attempts):
        if attempts == 6:
            print('                 ')
            print(' --------------  ')
            print(' |            |  ')
            print(' |            |  ')
            print(' |               ')
            print(' |               ')
            print(' |               ')
            print(' |               ')
            print(' |               ')
            print(' |               ')
        
        if attempts == 5:
            print('                 ')
            print(' --------------  ')
            print(' |            |  ')
            print(' |            |  ')
            print(' |            O  ')
            print(' |               ')
            print(' |               ')
            print(' |               ')
            print(' |               ')
            print(' |               ')

        if attempts == 4:
            print('                 ')
            print(' --------------  ')
            print(' |            |  ')
            print(' |            |  ')
            print(' |            O  ')
            print(' |            |  ')
            print(' |               ')
            print(' |               ')
            print(' |               ')
            print(' |               ')

        if attempts == 3:
            print('                 ')
            print(' --------------  ')
            print(' |            |  ')
            print(' |            |  ')
            print(' |            O  ')
            print(' |            |\ ')
            print(' |               ')
            print(' |               ')
            print(' |               ')
            print(' |               ')

        if attempts == 2:
            print('                 ')
            print(' --------------  ')
            print(' |            |  ')
            print(' |            |  ')
            print(' |            O  ')
            print(' |           /|\ ')
            print(' |               ')
            print(' |               ')
            print(' |               ')
            print(' |               ')

        if attempts == 1:
            print('                 ')
            print(' --------------  ')
            print(' |            |  ')
            print(' |            |  ')
            print(' |            O  ')
            print(' |           /|\ ')
            print(' |             \ ')
            print(' |               ')
            print(' |               ')
            print(' |               ')

        if attempts == 0:
            print('                 ')
            print(' --------------  ')
            print(' |            |  ')
            print(' |            |  ')
            print(' |            O  ')
            print(' |           /|\ ')
            print(' |           / \ ')
            print(' |               ')
            print(' |               ')
            print(' |               ')